<a href="https://colab.research.google.com/github/guneetnagia/LearnML/blob/data-preprocessing/Lab_Data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Titanic Dataset Preprocessing Assignment

In this assignment, we will preprocess the Titanic dataset to practice data cleaning, encoding, scaling, binarization, polynomial features, discretization, power transformation, and feature selection. We will use Scikit-learn's preprocessing functions to make the data ready for machine learning.

### Objectives:
- Handle missing values
- Encode categorical variables
- Scale features
- Apply binarization and discretization
- Generate polynomial features
- Perform power transformation
- Select the top features

In [3]:
# Loading the dataset
import pandas as pd
url = "/content/titanic.csv"
data = pd.read_csv(url)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [6]:
data.isnull()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

In [9]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [11]:
data.shape

(891, 12)

In [13]:
# Handling missing value
from sklearn.impute import SimpleImputer
# Impute numerical columns
imputer_num = SimpleImputer(strategy="median")
data["Age"] = imputer_num.fit_transform(data[["Age"]])
print("\nAfter imputing numerical columns:\n", data[["Age"]].head())

After imputing numerical columns:
     Age
0  22.0
1  38.0
2  26.0
3  35.0
4  35.0

In [15]:
# Impute categorical columns, since Embarked is categorial so most frequent fits
imputer_cat = SimpleImputer(strategy="most_frequent") # most frequent is mode
data["Embarked"] = imputer_cat.fit_transform(data[["Embarked"]]).ravel()
# ravel - for non integer, its 2d so use this
# This function flattens a multi-dimensional array into a 1-dimensional array.
print("\nAfter imputing categorical column 'Embarked':\n", data["Embarked"].head())

After imputing categorical column 'Embarked':
 0    S
1    C
2    S
3    S
4    S
Name: Embarked, dtype: object

In [19]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64